# Generated by Django 3.1.7 on 2022-12-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productId', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(max_length=100)),
                ('productPrice', models.FloatField()),
                ('productImage', models.CharField(max_length=400)),
                ('productDescription', models.CharField(max_length=500)),
            ],
        ),
    ]
