# Generated by Django 3.1.7 on 2022-12-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20221208_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Amount',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.address'),
        ),
    ]
